services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: notification-mq
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management UI dashboard
    networks:
      - notification-net

  producer:
    build:
      context: .
      args:
        - MODULE_NAME=producer
    container_name: notification-producer
    ports:
      - "8081:8081"
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq
    networks:
      - notification-net

  worker:
    build:
      context: .
      args:
        - MODULE_NAME=worker
    container_name: notification-worker
    ports:
      - "8082:8082"
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq
    networks:
      - notification-net

networks:
  notification-net:
    driver: bridge